<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Lokasi Wilayah _</name>
   <tag></tag>
   <elementGuidId>a627fa3d-e9fa-46d0-89f4-ec2b7348b493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'location_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Lokasi Wilayah *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>268b1e7a-50e5-4e77-9abd-3b0a765469a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>b1cd6a4a-45c5-4aac-9a2b-5f44133661dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location_id</value>
      <webElementGuid>dfd70de4-2b52-427c-8cb2-b86673aba099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location_id</value>
      <webElementGuid>a83126bc-71b3-48ff-83b0-d91945bb9d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Jakarta
                                                        Bandung
                                                        Surabaya
                                                        Medan
                                                        Makassar
                                                        Bali
                                                        Yogyakarta
                                                        Semarang
                                                        Malang
                                                        Remote
                                                    </value>
      <webElementGuid>cf610dcb-f472-4c42-ac2b-fedea13f6aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-61d023a1550b79ea0da4906891d698d9</value>
      <webElementGuid>127aff12-90ec-4bb6-8af3-a5605abd8c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'location_id']</value>
      <webElementGuid>e9df6c54-44b9-4009-b45c-e92cc165887a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'location_id']</value>
      <webElementGuid>7186a83e-6d58-4fc1-ba05-bccdb9fd9209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'location_id' and @name = 'location_id' and (text() = '
                                                        Jakarta
                                                        Bandung
                                                        Surabaya
                                                        Medan
                                                        Makassar
                                                        Bali
                                                        Yogyakarta
                                                        Semarang
                                                        Malang
                                                        Remote
                                                    ' or . = '
                                                        Jakarta
                                                        Bandung
                                                        Surabaya
                                                        Medan
                                                        Makassar
                                                        Bali
                                                        Yogyakarta
                                                        Semarang
                                                        Malang
                                                        Remote
                                                    ')]</value>
      <webElementGuid>44061a1a-8dbc-4b86-96bc-6783bf4be8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
