<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tuliskan poin-poin tanggung jawab peker</name>
   <tag></tag>
   <elementGuidId>c7740868-cc45-4b59-9c9c-97e599dec94c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'responsibilities']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#responsibilities</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tuliskan poin-poin tanggung jawab pekerjaan...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b3cab30-6d92-419b-bdd9-2f2ffd9d1fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>df9715b5-470b-4c30-9202-e59fdf97daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>responsibilities</value>
      <webElementGuid>04ec272d-1ece-438c-97b8-b178304e4f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>responsibilities</value>
      <webElementGuid>8a4d4bd9-bb2f-4fd4-87f8-20e878cbe1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>efa0c914-038f-430f-adac-566b356ace9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tuliskan poin-poin tanggung jawab pekerjaan...</value>
      <webElementGuid>08997d4a-5ac9-4764-8ccd-ed0cbe1914cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3bac6c989b696e35adda952b2c62089e</value>
      <webElementGuid>d5a0f347-9ba6-49d0-833d-902a6cf123a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'responsibilities']</value>
      <webElementGuid>ecd1f27a-9422-4672-b5d5-a438f5def4c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'responsibilities']</value>
      <webElementGuid>97632290-0da4-4b84-9f39-d49990964015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'responsibilities' and @name = 'responsibilities' and @placeholder = 'Tuliskan poin-poin tanggung jawab pekerjaan...']</value>
      <webElementGuid>2e976198-5479-4bb8-8fc8-76f39c12fbc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
