<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah</name>
   <tag></tag>
   <elementGuidId>1106234d-f0fd-4e5e-a7f7-6970d4d11908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-bs-target=&quot;\#modalExperience&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-bs-target = '#modalExperience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;+ Tambah&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb44151b-bf44-491b-9b01-5b17d2c9d613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary btn-sm rounded-pill px-3 fw-bold</value>
      <webElementGuid>55592f03-ea27-4317-bf41-2198de26dcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>8f038462-0601-48e9-b569-c93455ac2980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalExperience</value>
      <webElementGuid>f2683107-d9b7-4dbf-8432-a2aafdedc006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah</value>
      <webElementGuid>e1101cc2-c1fa-413e-9aae-483652eab2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1c67e63d5c3ef68d48c237210362b16c</value>
      <webElementGuid>42ac3c61-e3ef-49b5-9093-81a774ccc861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-bs-target = '#modalExperience']</value>
      <webElementGuid>76523eb9-d0d4-4d2f-b21a-9eadfcb3d95c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-bs-target = '#modalExperience']</value>
      <webElementGuid>f1076714-83c8-4fd1-bbd1-1be0e5eb4a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Tambah' or . = ' Tambah')]</value>
      <webElementGuid>d276640c-2d7a-4212-8836-a6a971e735cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
