<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah_1</name>
   <tag></tag>
   <elementGuidId>4841fefb-fe43-47e9-965e-d8675fe7c41d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-bs-target=&quot;\#modalEducation&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-bs-target = '#modalEducation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#history div >> internal:has-text=&quot;Pendidikan Tambah Belum ada riwayat pendidikan.&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb702d7b-fc00-40f3-9f52-07be347b18e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary btn-sm rounded-pill px-3 fw-bold</value>
      <webElementGuid>383a9508-27d5-4f72-904b-f68fa4e2bc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>9e363eb9-cafb-4030-a10b-5953979a037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalEducation</value>
      <webElementGuid>64bbaed3-8edc-45fb-b45c-fb59b5f3ac45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah</value>
      <webElementGuid>5a61dcde-e5c0-4985-8d36-a585d49bd2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f2d712ea724f1ae3b175e69ba21a95b</value>
      <webElementGuid>3a566332-449b-4afd-bbf5-94699826ab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-bs-target = '#modalEducation']</value>
      <webElementGuid>47f30748-b887-4768-98b1-766200c19af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-bs-target = '#modalEducation']</value>
      <webElementGuid>4d1bc096-871e-4c3c-b263-cd1a7c12e4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Tambah' or . = ' Tambah')]</value>
      <webElementGuid>0da39cb8-8d39-4041-985f-796092ebb217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
