<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_end_date_1</name>
   <tag></tag>
   <elementGuidId>e0e38b3b-6910-4b14-9593-2ba49a204e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalEducation [name=&quot;end_date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modalEducation']//*[@name = 'end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalEducation input[name=&quot;end_date&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba814f7b-aed8-4460-a0d0-e7a40b7d2e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>893ced93-060a-4c14-8a91-cbcfec1288af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>cdcb8050-5ec4-40b1-ab45-a573eeb4cfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9f415af1-f15f-46f8-b76a-607898adef8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b9e4a99105625428da7a67e08762085</value>
      <webElementGuid>60c3383f-1ef8-4c5e-8914-001924d02774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modalEducation']//*[@name = 'end_date']</value>
      <webElementGuid>4df84adb-65c6-4018-846b-37149fe6d855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modalEducation']//*[@name = 'end_date']</value>
      <webElementGuid>6ada6a60-76f7-4ba6-9f07-a86f913f888b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'end_date']</value>
      <webElementGuid>cedbc9a7-a454-4ad0-ac20-fa12aa15fdce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
