<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_resumeInput</name>
   <tag></tag>
   <elementGuidId>0500adb4-65b8-42ce-9fd6-ac4ea84bfd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resumeInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'resumeInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#resumeInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8482539-dfe4-421d-a8fc-d8dbf5a55f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>dbfdb321-5b8e-4cca-89ce-2d7fd48644ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resume</value>
      <webElementGuid>c222bc0d-c247-45e8-8b6f-8e6f9ee20d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none</value>
      <webElementGuid>212fb138-ad91-459a-a5bd-8935f6869e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resumeInput</value>
      <webElementGuid>c02dcec1-568a-47fd-b635-49ace79baed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>842d07e1-48cf-4eea-9aba-13e64ffbb32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9ae643dae651596b554248d328b5d1ca</value>
      <webElementGuid>c717e8ef-6ee0-4b91-b915-4ffd54fd3dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'resumeInput']</value>
      <webElementGuid>55cd340d-b833-44d8-ad2a-0d5a1569663f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'resumeInput']</value>
      <webElementGuid>5e07c49e-a58e-42ba-9a85-b07bf5ccfdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'resume' and @id = 'resumeInput']</value>
      <webElementGuid>a5d77c7f-69dc-4f44-8177-2326967b21e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
