<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_end_date</name>
   <tag></tag>
   <elementGuidId>af6c0041-3b20-4626-b0d1-4a8c4539423e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalExperience [name=&quot;end_date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modalExperience']//*[@name = 'end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalExperience input[name=&quot;end_date&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adfb6536-06ad-4f2b-a265-63bed133b247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8b2411d2-6641-426d-b11d-beb57ef67a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>0a9aada3-3d23-4479-aec0-032bd333b21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>deb1d866-b991-48cf-8645-332e54da1b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2f4e03149740bc2bfbfbfefe3acc10f8</value>
      <webElementGuid>6acf0a9e-2683-4ffe-ac21-c8adc5334669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modalExperience']//*[@name = 'end_date']</value>
      <webElementGuid>448db384-6432-461c-9794-d5b0172f2e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modalExperience']//*[@name = 'end_date']</value>
      <webElementGuid>6290d3bd-c0b4-49e1-b571-6f2cdfd62c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'end_date']</value>
      <webElementGuid>f94c936c-b646-4130-8985-32dd5b90b7f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
