<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Inggris</name>
   <tag></tag>
   <elementGuidId>82723a12-462d-440c-a864-30fe6c18ee21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;langInggris&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'langInggris']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Inggris&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ba7ead95-d52d-4789-bca3-17fb34dc03e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label fw-semibold w-100 py-2 border rounded-3 text-center cursor-pointer</value>
      <webElementGuid>91d10de0-ae47-47ae-ba70-b9ebd23cb107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>langInggris</value>
      <webElementGuid>a604b3f9-9d07-42ea-9583-8d004a2a7723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inggris</value>
      <webElementGuid>16d30237-0faa-4fca-95a0-a281e04fd677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-36bb42e2e921c0db940b270d5c11e971</value>
      <webElementGuid>d781b42f-da30-47e9-af48-be861c9ba73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'langInggris']</value>
      <webElementGuid>092cbef0-7bdb-41fd-9eb1-a62350ca0f7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'langInggris']</value>
      <webElementGuid>fe6a151c-37b7-4632-a70f-6a2b0a8c93c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Inggris' or . = 'Inggris')]</value>
      <webElementGuid>60f9df9c-7534-44fb-9c60-1ae9028064b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
